# Terraform root module. `terraform` runs here (working directory: services/).
# Per-service files (svc-<name>.tf) are generated by atlas-api and land in this
# directory, each calling the reusable ../modules/service module.

terraform {
  required_version = ">= 1.5"

  # The Terraform state is kept OUTSIDE the Actions runner working directory.
  # actions/checkout cleans the workspace (git clean -ffdx) at the start of every
  # run, which would delete a gitignored state file living next to the code and make
  # Terraform lose track of what it created (orphaned namespaces/databases). The
  # concrete absolute path is supplied at init time via -backend-config (see
  # .github/workflows/terraform.yml), keeping host specifics out of version control.
  backend "local" {}

  required_providers {
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.30"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }
}

variable "kube_context" {
  type        = string
  description = "kubeconfig context of the target cluster"
  default     = "kind-atlas-local"
}

# GHCR pull credentials, provided by the runner as TF_VAR_ghcr_username /
# TF_VAR_ghcr_token (GitHub Actions secrets). Each generated svc-<name>.tf passes
# these to the service module, which creates the ghcr-pull secret in the namespace.
# Never committed to git; kept only in tfstate (also gitignored).
variable "ghcr_username" {
  type        = string
  description = "GHCR username for pulling private service images"
  default     = ""
}

variable "ghcr_token" {
  type        = string
  description = "GHCR token (read:packages) for pulling private service images"
  default     = ""
  sensitive   = true
}

provider "kubernetes" {
  config_path    = "~/.kube/config"
  config_context = var.kube_context
}
