# Terraform root module. `terraform` runs here (working directory: services/).
# Per-service files (svc-<name>.tf) are generated by atlas-api and land in this
# directory, each calling the reusable ../modules/service module.

terraform {
  required_version = ">= 1.5"
  required_providers {
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.30"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }
}

variable "kube_context" {
  type        = string
  description = "kubeconfig context of the target cluster"
  default     = "kind-atlas-local"
}

provider "kubernetes" {
  config_path    = "~/.kube/config"
  config_context = var.kube_context
}
