# Generated by Atlas. Infrastructure for service eval01.
module "eval01" {
  source           = "../modules/service"
  name             = "eval01"
  database_enabled = true
  database_type    = "postgres"
  ghcr_username    = var.ghcr_username
  ghcr_token       = var.ghcr_token
}
