# Generated by Atlas. Infrastructure for service payments-service.
module "payments-service" {
  source           = "../modules/service"
  name             = "payments-service"
  database_enabled = true
  database_type    = "postgres"
  ghcr_username    = var.ghcr_username
  ghcr_token       = var.ghcr_token
}
