# Generated by Atlas. Infrastructure for service checkout.
module "checkout" {
  source           = "../modules/service"
  name             = "checkout"
  database_enabled = true
  database_type    = "postgres"
  ghcr_username    = var.ghcr_username
  ghcr_token       = var.ghcr_token
}
