# Generated by Atlas. Infrastructure for service billing.
module "billing" {
  source           = "../modules/service"
  name             = "billing"
  database_enabled = true
  database_type    = "postgres"
}
