# Generated by Atlas. Infrastructure for service orders-db.
module "orders-db" {
  source           = "../modules/service"
  name             = "orders-db"
  database_enabled = true
  database_type    = "postgres"
}
