# Generated by Atlas. Infrastructure for service orders-service.
module "orders-service" {
  source           = "../modules/service"
  name             = "orders-service"
  database_enabled = true
  database_type    = "postgres"
  ghcr_username    = var.ghcr_username
  ghcr_token       = var.ghcr_token
}
