# Reusable per-service infrastructure: a namespace and, optionally, a PostgreSQL
# instance. The database password is generated by Terraform and stored as an
# in-cluster Secret (kept in tfstate, never committed to git).

terraform {
  required_providers {
    kubernetes = { source = "hashicorp/kubernetes" }
    random     = { source = "hashicorp/random" }
  }
}

variable "name" {
  type        = string
  description = "service name (also the namespace)"
}

variable "database_enabled" {
  type    = bool
  default = false
}

variable "database_type" {
  type    = string
  default = ""
}

variable "ghcr_server" {
  type        = string
  description = "container registry host for the image pull secret"
  default     = "ghcr.io"
}

variable "ghcr_username" {
  type        = string
  description = "registry username for pulling private images (empty disables the pull secret)"
  default     = ""
}

variable "ghcr_token" {
  type        = string
  description = "registry token (read:packages) for pulling private images"
  default     = ""
  sensitive   = true
}

resource "kubernetes_namespace_v1" "this" {
  metadata {
    name   = var.name
    labels = { "app.kubernetes.io/part-of" = "atlas" }
  }
}

# Image pull secret so the service (private image in GHCR) can be pulled by the
# cluster. Credentials come from Terraform variables (provided by the runner as
# TF_VAR_ghcr_*), never committed to git. The base Helm chart references it by
# name (ghcr-pull). Created only when a token is provided.
resource "kubernetes_secret_v1" "ghcr_pull" {
  count = var.ghcr_token != "" ? 1 : 0
  metadata {
    name      = "ghcr-pull"
    namespace = kubernetes_namespace_v1.this.metadata[0].name
  }
  type = "kubernetes.io/dockerconfigjson"
  data = {
    ".dockerconfigjson" = jsonencode({
      auths = {
        (var.ghcr_server) = {
          username = var.ghcr_username
          password = var.ghcr_token
          auth     = base64encode("${var.ghcr_username}:${var.ghcr_token}")
        }
      }
    })
  }
}

resource "random_password" "db" {
  count   = var.database_enabled ? 1 : 0
  length  = 24
  special = false
}

resource "kubernetes_secret_v1" "db" {
  count = var.database_enabled ? 1 : 0
  metadata {
    name      = "postgres-credentials"
    namespace = kubernetes_namespace_v1.this.metadata[0].name
  }
  data = {
    POSTGRES_DB       = var.name
    POSTGRES_USER     = var.name
    POSTGRES_PASSWORD = random_password.db[0].result
  }
}

resource "kubernetes_stateful_set_v1" "postgres" {
  count = var.database_enabled ? 1 : 0
  metadata {
    name      = "postgres"
    namespace = kubernetes_namespace_v1.this.metadata[0].name
    labels    = { app = "postgres" }
  }
  spec {
    service_name = "postgres"
    replicas     = 1
    selector {
      match_labels = { app = "postgres" }
    }
    template {
      metadata {
        labels = { app = "postgres" }
      }
      spec {
        container {
          name  = "postgres"
          image = "postgres:16.4" # pinned patch tag
          port {
            container_port = 5432
          }
          env_from {
            secret_ref {
              name = kubernetes_secret_v1.db[0].metadata[0].name
            }
          }
          volume_mount {
            name       = "data"
            mount_path = "/var/lib/postgresql/data"
          }
          readiness_probe {
            exec {
              command = ["pg_isready", "-U", var.name, "-d", var.name]
            }
            initial_delay_seconds = 5
            period_seconds        = 10
          }
          liveness_probe {
            exec {
              command = ["pg_isready", "-U", var.name, "-d", var.name]
            }
            initial_delay_seconds = 15
            period_seconds        = 20
          }
          resources {
            requests = {
              cpu    = "50m"
              memory = "64Mi"
            }
            limits = {
              cpu    = "250m"
              memory = "256Mi"
            }
          }
        }
      }
    }
    volume_claim_template {
      metadata {
        name = "data"
      }
      spec {
        access_modes = ["ReadWriteOnce"]
        resources {
          requests = {
            storage = "1Gi"
          }
        }
      }
    }
  }
}

resource "kubernetes_service_v1" "postgres" {
  count = var.database_enabled ? 1 : 0
  metadata {
    name      = "postgres"
    namespace = kubernetes_namespace_v1.this.metadata[0].name
  }
  spec {
    selector = { app = "postgres" }
    port {
      port        = 5432
      target_port = 5432
    }
  }
}
