# Reusable per-service infrastructure: a namespace and, optionally, a PostgreSQL
# instance. The database password is generated by Terraform and stored as an
# in-cluster Secret (kept in tfstate, never committed to git).

terraform {
  required_providers {
    kubernetes = { source = "hashicorp/kubernetes" }
    random     = { source = "hashicorp/random" }
  }
}

variable "name" {
  type        = string
  description = "service name (also the namespace)"
}

variable "database_enabled" {
  type    = bool
  default = false
}

variable "database_type" {
  type    = string
  default = ""
}

resource "kubernetes_namespace_v1" "this" {
  metadata {
    name   = var.name
    labels = { "app.kubernetes.io/part-of" = "atlas" }
  }
}

resource "random_password" "db" {
  count   = var.database_enabled ? 1 : 0
  length  = 24
  special = false
}

resource "kubernetes_secret_v1" "db" {
  count = var.database_enabled ? 1 : 0
  metadata {
    name      = "postgres-credentials"
    namespace = kubernetes_namespace_v1.this.metadata[0].name
  }
  data = {
    POSTGRES_DB       = var.name
    POSTGRES_USER     = var.name
    POSTGRES_PASSWORD = random_password.db[0].result
  }
}

resource "kubernetes_stateful_set_v1" "postgres" {
  count = var.database_enabled ? 1 : 0
  metadata {
    name      = "postgres"
    namespace = kubernetes_namespace_v1.this.metadata[0].name
    labels    = { app = "postgres" }
  }
  spec {
    service_name = "postgres"
    replicas     = 1
    selector {
      match_labels = { app = "postgres" }
    }
    template {
      metadata {
        labels = { app = "postgres" }
      }
      spec {
        container {
          name  = "postgres"
          image = "postgres:16"
          port {
            container_port = 5432
          }
          env_from {
            secret_ref {
              name = kubernetes_secret_v1.db[0].metadata[0].name
            }
          }
        }
      }
    }
  }
}

resource "kubernetes_service_v1" "postgres" {
  count = var.database_enabled ? 1 : 0
  metadata {
    name      = "postgres"
    namespace = kubernetes_namespace_v1.this.metadata[0].name
  }
  spec {
    selector = { app = "postgres" }
    port {
      port        = 5432
      target_port = 5432
    }
  }
}
